services:

  frontendapp4-container:
    container_name: frontendapp4-container
    image: timothyfudocker/frontendapp4
    networks:
      - app-network  # Attach to the same network


  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/var/www/certbot/config
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network  # Attach to the same network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    #command: certonly --webroot -w /var/www/certbot --force-renewal --email timothyfuapple@gmail.com -d frontendapp4.duckdns.org --agree-tos
    command: certonly --webroot -w /var/www/certbot --config-dir /var/www/certbot/config --work-dir /var/www/certbot/work --logs-dir /var/www/certbot/logs --force-renewal --email timothyfuapple@gmail.com -d frontendapp4.duckdns.org --agree-tos
    networks:
      - app-network  # Attach to the same network

  nginx-https:
    container_name: nginx-https
    restart: unless-stopped
    image: nginx-https
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx-https.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/var/www/certbot/config
      - ./certbot/www:/var/www/certbot
    command: sudo systemctl stop nginx && sudo pkill -f nginx
    networks:
      - app-network  # Attach to the same network

networks:
  app-network:
    driver: bridge  # Define the network
