services:

  frontendapp4-container:
    container_name: frontendapp4-container
    image: timothyfudocker/frontendapp4
    networks:
      - app-network  # Attach to the same network

networks:
  app-network:
    driver: bridge  # Define the network
